Repository YCP-Swarm-Robotics-Capstone-2020-2021/swarm-website-backend, pull requests merged in 2021-02, with the labels that each got.

#66 Changed verify password to post request
  swarmdjango/core/views/userViewSet.py
Labels: bug, enhancement

#67 Feature/bean stalk
  .gitignore
  swarmdjango/.ebextensions/django.config
  swarmdjango/.gitignore
  swarmdjango/core/views_front.py
  swarmdjango/swarm_backend/settings.py
  swarmdjango/swarm_backend/urls.py
Labels: enhancement

#69 bugFix/prodRequests
  .gitignore
  swarmdjango/swarm_backend/settings.py
Labels: bug

#74 feature/changesRoute
  swarmdjango/core/views/entryViewSet.py
Labels: enhancement
